/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // 使用 CSS 变量，支持动态主题切换
        theme: {
          DEFAULT: 'var(--theme-color)',
          secondary: 'var(--theme-color-secondary)',
          tertiary: 'var(--theme-color-tertiary)',
          'lighter-1': 'var(--theme-color-lighter-1)',
          'lighter-2': 'var(--theme-color-lighter-2)',
          'lighter-3': 'var(--theme-color-lighter-3)',
          'lighter-4': 'var(--theme-color-lighter-4)',
          'lighter-5': 'var(--theme-color-lighter-5)',
          'lighter-6': 'var(--theme-color-lighter-6)',
          'lighter-7': 'var(--theme-color-lighter-7)',
          'lighter-8': 'var(--theme-color-lighter-8)',
          'lighter-9': 'var(--theme-color-lighter-9)',
          'darker-1': 'var(--theme-color-darker-1)',
          'darker-2': 'var(--theme-color-darker-2)',
          'darker-3': 'var(--theme-color-darker-3)',
          'darker-4': 'var(--theme-color-darker-4)',
          'darker-5': 'var(--theme-color-darker-5)',
          'darker-6': 'var(--theme-color-darker-6)',
          'darker-7': 'var(--theme-color-darker-7)',
          'darker-8': 'var(--theme-color-darker-8)',
          'darker-9': 'var(--theme-color-darker-9)',
        },
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
        green: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        accent: {
          warm: '#f59e0b',
          warmHover: '#f97316',
          warmMuted: '#fcd34d'
        },
        // 语义色系 - 基于UI/UX Pro Max最佳实践
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        info: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        }
      },
      fontFamily: {
        sans: ['Montserrat', 'Poppins', 'Roboto', 'Noto Sans SC', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Montserrat', 'Poppins', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        heading: ['Montserrat', 'system-ui', 'sans-serif'],
        body: ['Roboto', 'Noto Sans SC', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'theme': 'var(--border-radius)',
        'theme-lg': 'var(--border-radius-lg)',
        'theme-xl': 'var(--border-radius-xl)',
        'theme-2xl': 'var(--border-radius-2xl)',
      },
      boxShadow: {
        'theme': '0 4px 14px 0 rgba(37, 99, 235, 0.25)',
        'theme-lg': '0 10px 24px 0 rgba(37, 99, 235, 0.3)',
        'theme-glow': '0 0 24px rgba(37, 99, 235, 0.4)',
        'card': '0 2px 8px 0 rgba(0, 0, 0, 0.08)',
        'card-hover': '0 8px 24px 0 rgba(0, 0, 0, 0.12)',
        'sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'md': '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
        'lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-down': 'fadeInDown 0.6s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.5s ease-out',
        'slide-in-right': 'slideInRight 0.5s ease-out',
        'slide-in-bottom': 'slideInBottom 0.4s ease-out',
        'float': 'float 6s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float-delayed': 'float 6s cubic-bezier(0.4, 0, 0.6, 1) infinite 2s',
        'float-more-delayed': 'float 6s cubic-bezier(0.4, 0, 0.6, 1) infinite 4s',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 2s cubic-bezier(0.34, 1.56, 0.64, 1) infinite',
        'bounce-gentle': 'bounceGentle 2s cubic-bezier(0.34, 1.56, 0.64, 1) infinite',
        'spin-slow': 'spin 8s linear infinite',
        'wiggle': 'wiggle 1s cubic-bezier(0.34, 1.56, 0.64, 1) infinite',
        'glow': 'glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite alternate',
        'glow-pulse': 'glowPulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'scale-in': 'scaleIn 0.5s ease-out',
        'scale-in-smooth': 'scaleInSmooth 0.5s ease-out',
        'loading-bar': 'loadingBar 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'gradient-shift': 'gradientShift 4s ease infinite',
        'border-glow': 'borderGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'counter-up': 'counterUp 2s ease-out',
        'text-reveal': 'textReveal 0.8s ease-out',
        'card-entrance': 'cardEntrance 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInBottom: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px var(--theme-color-lighter-7)' },
          '100%': { boxShadow: '0 0 25px var(--theme-color-lighter-4), 0 0 40px var(--theme-color-lighter-6)' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 10px var(--theme-color-lighter-6)' },
          '50%': { boxShadow: '0 0 30px var(--theme-color-lighter-4), 0 0 50px var(--theme-color-lighter-5)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleInSmooth: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        loadingBar: {
          '0%': { left: '-100%', backgroundColor: 'var(--theme-color-lighter-7)' },
          '100%': { left: '100%', backgroundColor: 'var(--theme-color-lighter-4)' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        borderGlow: {
          '0%, 100%': { borderColor: 'var(--theme-color-lighter-5)' },
          '50%': { borderColor: 'var(--theme-color)' },
        },
        counterUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        textReveal: {
          '0%': { opacity: '0', transform: 'translateY(20px)', filter: 'blur(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)', filter: 'blur(0)' },
        },
        cardEntrance: {
          '0%': { opacity: '0', transform: 'translateY(40px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'theme-gradient': 'linear-gradient(135deg, var(--theme-color-lighter-3), var(--theme-color), var(--theme-color-darker-2))',
        'theme-gradient-soft': 'linear-gradient(135deg, var(--theme-color-lighter-8), var(--theme-color-lighter-6))',
      },
    },
  },
  plugins: [],
}