import { useCallback, useEffect, useState } from 'react'
import { RefreshCw, ShieldBan, ShieldCheck, TriangleAlert, Users } from 'lucide-react'
import type { AdminUser } from '@/services/authService'
import { securityApi, type DashboardData, type SecurityIp, type SecuritySettings } from '@/services/securityService'

const statusClass = { normal: 'text-emerald-700 bg-emerald-50', suspicious: 'text-amber-700 bg-amber-50', blocked: 'text-red-700 bg-red-50' }
const statusText = { normal: 'NORMAL', suspicious: 'SUSPICIOUS', blocked: 'BLOCKED' }

export function IpSecurityManagement({ user }: { user: AdminUser | null }) {
  const canManage = user?.role === 'super_admin'
  const [tab, setTab] = useState<'dashboard' | 'ips' | 'settings' | 'whitelist'>('dashboard')
  const [dashboard, setDashboard] = useState<DashboardData | null>(null); const [ips, setIps] = useState<SecurityIp[]>([])
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [selected, setSelected] = useState<Awaited<ReturnType<typeof securityApi.detail>>['data']>()
  const [settings, setSettings] = useState<SecuritySettings | null>(null); const [whitelist, setWhitelist] = useState<Array<{ ip: string; note?: string }>>([])
  const load = useCallback(async () => { const [d, list, s, w] = await Promise.all([securityApi.dashboard(), securityApi.ips({ page: 1, limit: 50, ip: search, status }), securityApi.settings(), securityApi.whitelist()]); if (d.data) setDashboard(d.data); if (list.data) setIps(list.data.items); if (s.data) setSettings(s.data); if (w.data) setWhitelist(w.data) }, [search, status])
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 30000); return () => clearInterval(timer) }, [load])
  const manage = async (ip: string, block: boolean) => { if (!canManage) return; if (block) { const reason = window.prompt('封禁原因', '手动封禁'); if (!reason) return; const duration = window.prompt('封禁小时数（留空为永久）', '24'); await securityApi.ban(ip, reason, duration ? Number(duration) : undefined) } else await securityApi.unban(ip); await load() }
  return <div className="p-6 space-y-5 text-slate-900 dark:text-slate-100">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">IP 安全防护中心</h1><p className="text-sm text-slate-500">监控异常流量并联动 Nginx / CrowdSec</p></div><button onClick={() => void load()} className="flex items-center gap-2 rounded-lg border px-3 py-2"><RefreshCw className="h-4 w-4"/>刷新</button></div>
    {!canManage && <div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">普通管理员为只读模式；封禁、解封、设置和白名单操作仅超级管理员可用。</div>}
    <div className="flex gap-2 border-b">{(['dashboard','ips','settings','whitelist'] as const).map(v => <button key={v} onClick={() => setTab(v)} className={`px-3 py-2 ${tab===v?'border-b-2 border-blue-600 text-blue-600':''}`}>{({dashboard:'概览',ips:'IP 记录',settings:'安全设置',whitelist:'IP 白名单'} as const)[v]}</button>)}</div>
    {tab === 'dashboard' && dashboard && <><div className="grid gap-4 md:grid-cols-4">{[[Users,'当前访问 IP',dashboard.activeIps],[ShieldBan,'当前封禁 IP',dashboard.blockedIps],[TriangleAlert,'可疑 IP',dashboard.suspiciousIps],[ShieldCheck,'今日异常请求',dashboard.attacksToday]].map(([Icon,label,value]) => { const C=Icon as typeof Users; return <div className="rounded-xl border bg-white p-4 dark:bg-slate-800" key={String(label)}><C className="mb-3 h-5 w-5 text-blue-600"/><div className="text-2xl font-bold">{String(value)}</div><div className="text-sm text-slate-500">{String(label)}</div></div>})}</div><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border p-4"><h3 className="mb-3 font-semibold">Top 请求 IP</h3>{dashboard.topRequestIps.map(i=><div key={i.ip} className="flex justify-between border-b py-2 text-sm"><button className="text-blue-600" onClick={async()=>{setSelected((await securityApi.detail(i.ip)).data);setTab('ips')}}>{i.ip}</button><span>{i.requestCount.toLocaleString()} requests</span></div>)}</section><section className="rounded-xl border p-4"><h3 className="mb-3 font-semibold">最近攻击事件</h3>{dashboard.recentEvents.map(e=><div key={e._id} className="grid grid-cols-[auto_1fr_auto] gap-3 border-b py-2 text-sm"><span>{new Date(e.createdAt).toLocaleTimeString()}</span><span>{e.ip}</span><span>{e.rule}</span></div>)}</section></div></>}
    {tab === 'ips' && <><div className="flex gap-2"><input className="rounded-lg border bg-transparent px-3 py-2" placeholder="搜索 IP" value={search} onChange={e=>setSearch(e.target.value)}/><select className="rounded-lg border bg-transparent px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option><option value="normal">Normal</option><option value="suspicious">Suspicious</option><option value="blocked">Blocked</option></select></div><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{['IP','请求次数','频率','最后访问','URL','状态','操作'].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{ips.map(i=><tr key={i.ip} className="border-t"><td className="p-3 font-mono">{i.ip}</td><td>{i.requestCount}</td><td>{i.requestsPerMinute}/min</td><td>{new Date(i.lastSeenAt).toLocaleString()}</td><td className="max-w-xs truncate">{i.lastUrl}</td><td><span className={`rounded-full px-2 py-1 text-xs ${statusClass[i.status]}`}>{statusText[i.status]}</span></td><td className="space-x-2"><button className="text-blue-600" onClick={async()=>setSelected((await securityApi.detail(i.ip)).data)}>查看</button>{canManage && (i.status==='blocked'?<button className="text-emerald-600" onClick={()=>void manage(i.ip,false)}>解封</button>:<button className="text-red-600" onClick={()=>void manage(i.ip,true)}>封禁</button>)}</td></tr>)}</tbody></table></div>{selected && <div className="rounded-xl border p-4"><div className="flex justify-between"><h3 className="font-semibold">IP 详情：{selected.summary?.ip}</h3><button onClick={()=>setSelected(undefined)}>关闭</button></div><p className="mt-2 text-sm">首次访问：{new Date(selected.summary.firstSeenAt).toLocaleString()} · 最后访问：{new Date(selected.summary.lastSeenAt).toLocaleString()} · User-Agent：{selected.summary.lastUserAgent}</p><h4 className="mt-4 font-medium">最近请求</h4>{selected.requests.map((r,index)=><div key={index} className="grid grid-cols-6 gap-2 border-b py-2 text-xs"><span>{new Date(r.time).toLocaleString()}</span><span>{r.method}</span><span className="col-span-2 truncate">{r.url}</span><span>{r.statusCode}</span><span>{r.responseTimeMs}ms</span></div>)}<h4 className="mt-4 font-medium">安全事件</h4>{selected.events.map(e=><div key={e._id} className="border-b py-2 text-sm">{e.rule} · {e.details}</div>)}</div>}</>}
    {tab === 'settings' && settings && <div className="max-w-3xl rounded-xl border p-5"><div className="grid gap-4 md:grid-cols-2">{([['requestsPerMinute','每分钟最大请求数'],['hardLimit','自动封禁硬阈值'],['apiRequestsPerMinute','API 每分钟限制'],['loginFailures','登录失败次数'],['notFoundThreshold','404 请求阈值'],['suspiciousThreshold','可疑阈值'],['defaultBanDurationHours','默认封禁小时数']] as const).map(([key,label])=><label key={key} className="text-sm">{label}<input disabled={!canManage} type="number" className="mt-1 w-full rounded-lg border bg-transparent p-2" value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}</div><div className="mt-4 flex gap-5">{([['autoBan','自动封禁'],['autoUnban','自动解封'],['crowdsecEnabled','CrowdSec 集成']] as const).map(([key,label])=><label key={key}><input disabled={!canManage} type="checkbox" checked={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/> {label}</label>)}</div>{canManage&&<button className="mt-5 rounded-lg bg-blue-600 px-4 py-2 text-white" onClick={async()=>{await securityApi.updateSettings(settings);await load()}}>保存设置</button>}</div>}
    {tab === 'whitelist' && <div className="max-w-3xl rounded-xl border p-5">{canManage&&<button className="mb-4 rounded-lg bg-blue-600 px-4 py-2 text-white" onClick={async()=>{const ip=window.prompt('IP 地址');if(!ip)return;const note=window.prompt('备注','')||'';await securityApi.addWhitelist(ip,note);await load()}}>添加白名单</button>}{whitelist.map(w=><div className="flex justify-between border-b py-3" key={w.ip}><span><span className="font-mono">{w.ip}</span> <span className="text-sm text-slate-500">{w.note}</span></span>{canManage&&<button className="text-red-600" onClick={async()=>{await securityApi.removeWhitelist(w.ip);await load()}}>删除</button>}</div>)}</div>}
  </div>
}
